name: React CD

on:
  workflow_run:
    workflows: ["React Typescript CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - name: Download code repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './budget-tracker-react/package-lock.json'
          
      - name: Install and build
        working-directory: ./budget-tracker-react
        run: |
          npm ci
          npm run build
