# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React Typescript CI

on:
  push:
    branches: [master, dev, main]
  pull_request:
    branches: [master, dev, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './budget-tracker-react/package-lock.json'
          
      - name: Install dependencies
        working-directory: ./budget-tracker-react  
        run: npm ci

      - name: Check data type
        working-directory: ./budget-tracker-react  
        run: npx tsc --noEmit

      - name: Run tests (if any exist)
        working-directory: ./budget-tracker-react 
        run: npm test --if-present

      - name: Build project
        working-directory: ./budget-tracker-react  
        run: npm run build
